# Generated by Django 3.2.5 on 2021-07-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleTarifaECT', '0002_auto_20210706_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifa',
            old_name='peso',
            new_name='peso_F',
        ),
        migrations.AddField(
            model_name='tarifa',
            name='peso_I',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
