# Generated by Django 3.2.5 on 2021-07-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleTarifaECT', '0003_auto_20210721_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='peso_F',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='peso_I',
            field=models.IntegerField(),
        ),
    ]
